version: 2.1
orbs:
  slack: circleci/slack@4.4.2
  aws-s3: circleci/aws-s3@2.0.0
jobs:
  build:
    docker:
      - image: circleci/node # ジョブのコマンドが実行されるプライマリ コンテナ

    environment:
      - AWS_S3_BUCKET_NAME: wppdx3learning
      - AWS-ACCESS-KEY-ID: 
      - AWS-REGION: 
      - AWS-SECRET-ACCESS-KEY: 
    steps:
      - checkout # プロジェクト ディレクトリ内のコードをチェック アウトします
      - run : 
          name: Build front-end
          command: |
            npm install
            npm run build
      # - run:
      #     name: Deploy to S3 if branch is Master.
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == "develop" ]; then
      #         aws s3 sync ~/dist s3://${AWS_S3_BUCKET_NAME}/ --exact-timestamps --delete
      #       fi
      - aws-s3/copy:
          aws-access-key-id: ${AWS-ACCESS-KEY-ID}
          aws-region: ${AWS-REGION}
          aws-secret-access-key: ${AWS-SECRET-ACCESS-KEY}
          from: '/dist/'
          to: 's3:/${AWS_S3_BUCKET_NAME}'
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies
      - store_artifacts:
          path: dist
  test:
    docker:
      - image: circleci/node:12-browsers 
    steps:
      - checkout # プロジェクト ディレクトリ内のコードをチェック アウトします
      - restore_cache:
          key: v1-dependencies
      - run : 
          name: Test front-end
          command: |
            npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build