version: 2.1
orbs:
  slack: circleci/slack@4.4.2
jobs:
  build:
    docker:
      - image: circleci/node # ジョブのコマンドが実行されるプライマリ コンテナ
    steps:
      - checkout # プロジェクト ディレクトリ内のコードをチェック アウトします
      - run : 
          name: Build front-end
          command: |
            npm install
            npm run build
      - slack/notify:
          event: pass
          template: basic_fail_1
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies
      - store_artifacts:
          path: dist
  test:
    docker:
      - image: circleci/node:12-browsers 
    steps:
      - checkout # プロジェクト ディレクトリ内のコードをチェック アウトします
      - restore_cache:
          key: v1-dependencies
      - run : 
          name: Test front-end
          command: |
            npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  deploy:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            curl -sL https://rpm.nodesource.com/setup_12.x | bash -
            yum install -y nodejs
      - run:
          name: Front Build
          command: |
            npm install
            npm run build
      - run:
          name: Deploy to S3
          command: 
            aws s3 cp ./dist s3://dx3-ci-angular --recursive

workflows:
  my_workflow:
    jobs:
      - deploy
      # - build
      # - test:
      #     requires:
      #       - build